### ISSUE TITLE
the bible passage is blank with errors

### ISSUE THREAD

**Issue by myjeshurun** [selfire1/BibleGateway-to-Obsidian#10]
Hello my brohter, I have a problem with the setup,
I follow the instructions to put bg2obs.sh and bg2md.rb together, run bash bg2obs.sh, then I got a screen of this:

Traceback (most recent call last):
	2: from bg2md.rb:77:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- colorize (LoadError)

And in the directory, I have bible passage files, but they are blank like this:

# Genesis 1

[[Genesis]] | [[Gen-02|Genesis 02 →]]

***

***

[[Genesis]] | [[Gen-02|Genesis 02 →]]

Would you please to help me?

**Comment by myjeshurun** [comment]
here is my ruby version: ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

**Comment by myjeshurun** [comment]
I surveyed the forum: https://forum.obsidian.md/t/bible-study-in-obsidian-kit-including-the-bible-in-markdown/12503/66, and find the answer:

> I think you might have missed a small step in the installation.

In the error output you can see cannot load such file -- colorize. That leads me to believe that the colorize module might not be installed. Have a look at the bg2md installation guide 6 or try running sudo gem install colorize optparse clipboard .

Let me know if that worked!

**Comment by selfire1** [comment]
Hey @myjeshurun, thanks for submitting the issue! Did it work for you when trying those steps?

**Comment by shawnhansen** [comment]
I had the same issue and after `sudo gem install colorize optparse clipboard` it worked.
