### ISSUE TITLE
Deleting cross references

### ISSUE THREAD

**Issue by mikenlee** [selfire1/BibleGateway-to-Obsidian#12]
Hello Joshua. Can you clarify what you meant by the line: \<crossref intro.*crossref\>
Should this be run in the terminal? 
Thanks for your work on this!

**Comment by selfire1** [comment]
Hi! You can open up Obsidian in a text editor like `VSCode` or `Atom`. Run find and replace with regex on!

**Comment by selfire1** [comment]
This is implemented now in the script.
