### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by skierkcity** [selfire1/BibleGateway-to-Obsidian#13]
Hello!

I am self-educated in scripts etc and have had a bit of trouble when running the script.

The error I run into is the following line:
```
bg2obs.sh: line 148: ruby: command not found
```
For every single line that the script runs.

I have Ruby and Perl installed and have tried running the script through PowerShell. Both scripts are also in the same directory.

**Comment by selfire1** [comment]
This looks like an incomplete ruby installation.

open the terminal app and try `ruby --version` > what does it print on the terminal?
