### ISSUE TITLE
I get an Error on select books of the bible

### ISSUE THREAD

**Issue by newbonedayatatime** [selfire1/BibleGateway-to-Obsidian#17]
Hi,

I appreciate your work on this. For some reason I am getting an error on a few books of the bible. This does not happen to all. It only happens to the books of the bible that have either 1, 2, or 3 before it. So the specific books of the bible are: 1 Chronicles, 1 Corinthians, 1 John, 1 Kings, 1 Peter, 1 Samuel, 1 Thessalonians, 1 Timothy, 2 Corinthians, 2 John, 2 Kings, 2 Peter, 2 Samuel, 2 Thessalonians, 2 Timothy, 3 John. All the other books that do not have a number before the name of the book are working perfectly. 

I tried doing this for esv, niv, and nlt. All the same issue. This is the error I am getting:

[0;31;49mError: could not parse data from BibleGateway: please check your usage, and if still a problem, please raise an issue on GitHub.[0m

I am not sure if it is your program or a bible gateway issue. Would you happen to know how to fix it?

OS:
Big Sur 11.6.2

Ruby Version:
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20]

Gem List:
*** LOCAL GEMS ***

abbrev (default: 0.1.0)
base64 (default: 0.1.0)
benchmark (default: 0.1.1)
bigdecimal (default: 3.0.0)
bundler (default: 2.2.32)
cgi (default: 0.2.1)
clipboard (1.3.6)
colorize (0.8.1)
csv (default: 3.1.9)
date (default: 3.1.3)
dbm (default: 1.1.0)
debug (default: 0.2.1)
delegate (default: 0.2.0)
did_you_mean (default: 1.5.0)
digest (default: 3.0.0)
drb (default: 2.0.5)
english (default: 0.7.1)
erb (default: 2.2.0)
etc (default: 1.3.0)
fcntl (default: 1.0.1)
fiddle (default: 1.0.8)
fileutils (default: 1.5.0)
find (default: 0.1.0)
forwardable (default: 1.3.2)
getoptlong (default: 0.1.1)
io-console (default: 0.5.7)
io-nonblock (default: 0.1.0)
io-wait (default: 0.2.0)
ipaddr (default: 1.2.2)
irb (default: 1.3.5)
json (default: 2.5.1)
logger (default: 1.4.3)
matrix (default: 0.3.1)
minitest (5.14.2)
mutex_m (default: 0.1.1)
net-ftp (default: 0.1.2)
net-http (default: 0.1.1)
net-imap (default: 0.1.1)
net-pop (default: 0.1.1)
net-protocol (default: 0.1.1)
net-smtp (default: 0.2.1)
nkf (default: 0.1.0)
observer (default: 0.1.1)
open-uri (default: 0.1.0)
open3 (default: 0.1.1)
openssl (default: 2.2.1)
optparse (0.2.0, default: 0.1.1)
ostruct (default: 0.3.1)
pathname (default: 0.1.0)
power_assert (1.2.0)
pp (default: 0.2.1)
prettyprint (default: 0.1.1)
prime (default: 0.1.2)
pstore (default: 0.1.1)
psych (default: 3.3.2)
racc (default: 1.5.2)
rake (13.0.3)
rbs (1.4.0)
rdoc (default: 6.3.3)
readline (default: 0.0.2)
readline-ext (default: 0.1.1)
reline (default: 0.2.5)
resolv (default: 0.2.1)
resolv-replace (default: 0.1.0)
rexml (3.2.5)
rinda (default: 0.1.1)
rss (0.2.9)
securerandom (default: 0.1.0)
set (default: 1.0.1)
shellwords (default: 0.1.0)
singleton (default: 0.1.1)
stringio (default: 3.0.1)
strscan (default: 3.0.1)
syslog (default: 0.1.0)
tempfile (default: 0.1.1)
test-unit (3.3.7)
time (default: 0.1.0)
timeout (default: 0.1.1)
tmpdir (default: 0.1.2)
tracer (default: 0.1.1)
tsort (default: 0.1.0)
typeprof (0.15.2)
un (default: 0.1.0)
uri (default: 0.10.1)
weakref (default: 0.1.1)
yaml (default: 0.1.1)
zlib (default: 2.0.0)

Thx!

**Comment by unspokendeed** [comment]
I am experiencing the same issue - the error occurs on books with a number before the book name.

**Comment by newbonedayatatime** [comment]
it is nice to know I am not the only one! 
Thank you for commenting.

**Comment by selfire1** [comment]
That's odd. I'll look into it when I get to it!

**Comment by newbonedayatatime** [comment]
> That's odd. I'll look into it when I get to it!

Thank you so much!

**Comment by selfire1** [comment]
This should be fixed with bdee6b606d82cc1eceb0ae644bfeb364a99f1268

**Comment by newbonedayatatime** [comment]
Thank you so much. It works!
