### ISSUE TITLE
I get the chapter file without break lines

### ISSUE THREAD

**Issue by edunet22** [selfire1/BibleGateway-to-Obsidian#25]
Hi!
How can I ask the script to break each line y a new line.
It makes no sense for obsidian because it cannot get the headings (dividing verses).

This is what I get:
`# Genesis 1
***

# Genesis 1 (World English Bible) ##### Chapter 1 ###### 1 In the beginning, God created the heavens and the earth. ###### 2 The earth was formless and empty. Darkness was on the surface of the deep and God's Spirit was hovering over the surface of the waters. ###### 3 God said, "Let there be light," and there was light. ###### 4 God saw the light, and saw that it was good. God divided the light from the darkness. ###### 5 God called the light "day", and the darkness he called "night". There was evening and there was morning, the first day. ###### 6 God said, "Let there be an expanse in the middle of the waters, and let it divide the waters from the waters." ###### 7 God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so. ###### 8 God called the expanse "sky". There was evening and there was morning, a second day. `

**Comment by edunet22** [comment]
Done!!!
Changing ruby file:
`# simplify verse/chapters numbers (or remove entirely if that option set)
if opts[:numbering]
  # Now see whether to start chapters and verses as H5 or H6 
  if opts[:newline]
    # Extract the contents of the 'versenum' class (which should just be numbers, but we're not going to be strict)
    passage.gsub!(%r{<sup class="versenum">\s*(\d+-?\d?)\s*</sup>}, "\\n ###### v\\1 \\n ")
    # verse number '1' seems to be omitted if start of a new chapter, and the chapter number is given.
    passage.gsub!(%r{<span class="chapternum">\s*(\d+)\s*</span>}, "\\n ##### Capítulo \\1 \\n ###### v1 \\n ")
  else
    # Extract the contents of the 'versenum' class (which should just be numbers, but we're not going to be strict)
    passage.gsub!(%r{<sup class="versenum">\s*(\d+-?\d?)\s*</sup>}, '\1 ')
    # verse number '1' seems to be omitted if start of a new chapter, and the chapter number is given.
    passage.gsub!(%r{<span class="chapternum">\s*(\d+)\s*</span>}, '\1:1 ')
  end
else
  passage.gsub!(%r{<sup class="versenum">.*?</sup>}, '')
  passage.gsub!(%r{<span class="chapternum">.*?</span>}, '')
end`

**Comment by fivestones** [comment]
Edit the file bg2obs.sh.

Change line 182 from `text=$(echo $text | sed 's/^(.*?)v1/v1/') # Deleting unwanted headers` to `text=$(echo "$text" | sed 's/^(.*?)v1/v1/') # Deleting unwanted headers`

Then change line 229 from `echo -e $export >> "$filename.md"` to `echo -e "$export" >> "$filename.md"`

Save the file and try again. That fixed the problem for me

**Comment by rodydavis** [comment]
> Edit the file bg2obs.sh.
> 
> Change line 182 from `text=$(echo $text | sed 's/^(.*?)v1/v1/') # Deleting unwanted headers` to `text=$(echo "$text" | sed 's/^(.*?)v1/v1/') # Deleting unwanted headers`
> 
> Then change line 229 from `echo -e $export >> "$filename.md"` to `echo -e "$export" >> "$filename.md"`
> 
> Save the file and try again. That fixed the problem for me

That worked for me too!
