### ISSUE TITLE
HFA downloaded: Error in 5. Mose

### ISSUE THREAD

**Issue by tschomacker** [selfire1/BibleGateway-to-Obsidian#26]
I downloaded the HFA bible with the German-Version of the tool. Everything looked fine until I came across some headings in 5. Mose: Every time the verse number is not only a number but a range of numbers the headline is mal-formatted like this: `<sup class="versenum">54-55</sup>`. I fixed It by hand but I think it is a general parsing error.

**Comment by koel188** [comment]
Hallo! Würdest du mir deine md-Datei der HFA teilen? Ich bin auch noch daran, Übersetzungen zu importieren...

Herzlichen Dank!

**Comment by tschomacker** [comment]
Hallo @koel188 ich fühle mich urheberrechtsmäßig nicht so wohl, dass hier öffentlich hochzuladen. Könnte ich dir irgendwo direkt schreiben?

**Comment by koel188** [comment]
Lieber Thorben

Danke, kann ich verstehen! Klar, meine Email lautet ***@***.***

Vielen Dank schon im Voraus!

Noel

Von meinem iPhone gesendet

**Comment by tschomacker** [comment]
Hi Noel, leider wurde deine Mail rausgefiltert. Kannst du Sie nochmal in dem Format hinterlassen: name (at) domain . de . Oder in deinem Profil hinterlegen.

**Comment by koel188** [comment]
Hallo Thorben,

Klar, da müssen wir wieder mal das System hintergehen ;)

koel . nipfer at gmail . com

Besten Dank im Voraus noch einmal!

Noel

**Comment by koel188** [comment]
Hallo Thorben,

Klar, da müssen wir wieder mal das System hintergehen ;)

koel . nipfer at gmail . com

Besten Dank im Voraus noch einmal!

Noel

**Comment by selfire1** [comment]
Closed as stale. Likely fixed in the current iteration. Feel free to create another issue if this is still a problem.
