### ISSUE TITLE
Just wanted to say Thanks!

### ISSUE THREAD

**Issue by daribock** [selfire1/BibleGateway-to-Obsidian#29]
Hello Joschua,

I am just stoping by to say Thank you! Great script you wrote here for us, the time, and effort you must have put into this, crazy! I wanted to contact on E-Mail you put it seems like you [contact me](https://joschuasgarden.com/50+Slipbox/Contact+me) page on obsidian is outdated (or you are busy at the moment). 😢 
I would love to chat with you a little bit more about your project, what your future plans are and especially what god is doing in your life.

Again great, great job! May God bless you and keep the good stuff going! 🔥

PS.: While I wrote this I started the script and I discovered that you can't use ctrl + v while the script is running. This would be probably not bad to mention in the README.

**Comment by selfire1** [comment]
Hi Darius,

really appreciate your kind words. That's really encouraging!

Sorry I didn't get back to you! For some reason no email arrived on my end 🤷‍♂️ I sent you an email to the address mentioned in your Github profile :)

I'll mention the usage of the clipboard in the readme, thanks!
