### ISSUE TITLE
Books beginning with a number not working.

### ISSUE THREAD

**Issue by koel188** [selfire1/BibleGateway-to-Obsidian#31]
Hi,
First of all THANK YOU!! You're doing a great work!

I've had a smaller issue with importing the Bible books from biblegateway.com. All the books work fine **except books that begin with a number** (e.g. 1. Timothy, 2. Chronicles ect.).

Do you know how I can fix this?

Thank you in advance!!

**Comment by alexdicant** [comment]
Were you able to solve? I have the same problem.

**Comment by koel188** [comment]
Yes I was! I had to change something in an index list. Please contact me again in a couple days if you want to know more about it. We're having a wedding on Saturday. :)Greetings from Switzerland!NoelSent from my iPhoneOn 31 Aug 2023, at 00:54, alexdicant ***@***.***> wrote:﻿
Were you able to solve? I have the same problem.

**Comment by KardKibitzer** [comment]
@koel188 I'm having the same problem. What was you solution?

**Comment by selfire1** [comment]
Closed with #47
