### ISSUE TITLE
Problem with the bg2obs.sh for french

### ISSUE THREAD

**Issue by gregoirealvarez777** [selfire1/BibleGateway-to-Obsidian#34]
I'm a real beginner with all of this, but I finally success to download the Bible version I want in markdown with the scripts you provide, THANKS !!!

But after a lot of try, the process started with the FR version of the script but at the end I get all the folders and file, but with always the chapter one of the book itself...

So I try again and again, in different way and at some point I tried with the original bg2obs.sh, I selected a French version, and it worked well.

So I think that there is a mistake inside the French script of the bg2obs.sh script, or maybe I didn't underwent something which is totally possible 😅

But again a big THANK YOU !

**Comment by selfire1** [comment]
Should be fixed with https://github.com/selfire1/BibleGateway-to-Obsidian/commit/7ec0b78d4cbbf8591efcc1ea58f427917c94ef78
