### ISSUE TITLE
Acts of the Apostles not loading

### ISSUE THREAD

**Issue by qwarz212** [selfire1/BibleGateway-to-Obsidian#37]
For all the chapter of Acts, I get the following .md content after following the  mkudija/BibleGateway-to-Obsidian-Catholic instructions:

---
Aliases: [Acts of the Apostles 5]
---
# Acts of the Apostles 5 (RSVCE)

 [[Acts-04|← Acts of the Apostles 04]] | [[Acts of the Apostles]] | [[Acts-06|Acts of the Apostles 06 →]] | [Bible Gateway: Acts of the Apostles 5](https://www.biblegateway.com/passage/?search=Acts%20of%20the%20Apostles+5&version=RSVCE)
***

[0;31;49mError: found no useful lines in HTML data, so stopping. [0m

***
[[Acts-04|← Acts of the Apostles 04]] | [[Acts of the Apostles]] | [[Acts-06|Acts of the Apostles 06 →]] | [Bible Gateway: Acts of the Apostles 5](https://www.biblegateway.com/passage/?search=Acts%20of%20the%20Apostles+5&version=RSVCE)

**Comment by cjolson** [comment]
Same. I also could not get any of Acts

**Comment by cjolson** [comment]
@qwarz212 I fixed it. On line 61 in `bg2obs.sh`, the Catholic version lists Acts as "Acts of the Apostles". Change it to just "Acts" and it should be good.
