### ISSUE TITLE
perl find replace not working

### ISSUE THREAD

**Issue by joos13** [selfire1/BibleGateway-to-Obsidian#4]
![IMG_3885](https://user-images.githubusercontent.com/5041750/114932305-526f8f00-9e05-11eb-9760-105957128af3.jpeg)

When I run the script to pull the NIV version (or any other version that I've tried), the headers are not removed and the verses are not handled correctly either. Screenshot shows my output. Thanks @timwilson !

**Comment by joos13** [comment]
I just realized I skipped the step:

"Add the .rb script to your path, and then set it as executable (chmod 755 np*.rb)."

I don't really understand what that means. Can I get a little help on that?

**Comment by timwilson** [comment]
@joos13 The easiest thing to do is just put a copy of the `bg2md.rb` script in the same directory as the `bg2obs.sh` script. Then you can just set the permissions like you did:

```
chmod 755 bg2md.rb
```

The `chmod` command is a way of adjusting the permissions on files. Using the 755 is just a shortcut to make sure that any user is able to execute the script. As with any thing unix, all the options are documented if you type `man chmod`.

You didn't say what kind of OS you're using, but you'll need perl installed to do the parts of the script that fix the formatting. I'm familiar with macOS and Linux, so I don't know about installing perl on a Windows system if that's what you're using.

**Comment by joos13** [comment]
Thanks, I tried all those steps and am still getting the same output. I'm on macOS with Perl installed. It's probably more an issue with me than the code. It seems pretty straightforward so I must be missing a step.

**Comment by joos13** [comment]
User error confirmed. I was quitting the script without letting it run all the way as a test...not realizing the markdown cleanup runs after all the files are created. So I never gave the perl a chance to run. Sorry!
