### ISSUE TITLE
Language not found

### ISSUE THREAD

**Issue by PetterKringberg** [selfire1/BibleGateway-to-Obsidian#44]
Hello,
many thanks for uploading this. However, I have run into a problem - not sure if it's me being stupid or not, but when I run` bash bg2obs.sh`, I first get this question:

I confirm that I have checked and understand the copyright/license conditions for  and wish to continue downloading it in its entirety?
1) Yes
2) No
#? 

And when I answer 1 for yes, I get

cat: ./locales/en/name.txt: No such file or directory
Language not found!

I'm sure it's something I'm doing wrong, but what?

Many thanks in advance,
Petter

**Comment by kelseyswilliams** [comment]
@Lucas-Froguel H, I am having this same issue and feel completely lost as to what I need to do to download the whole code/folders. I have found the locales folder on GitHub but can't figure out how to download it. Do I need the entire locales folder or just the language I am interested in (e.g., "en")?

Are there other folders? When you say "whole code" do mean another code other than bg2md.rb and bg2obs.sh?
