### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by MadBomber** [selfire1/BibleGateway-to-Obsidian#50]
running the script generates a nice directory structure with files appropriately named that have the yaml front matter - and nothing else.  The verbose feedback is showing an error message of no such file or directory.  My best guess is the BG has changed their interface.

**Comment by jackediroh** [comment]
I am having the same issue unfortunately.

**Comment by selfire1** [comment]
Hi! Thanks for raising this. It's on my list to investigate.

**Comment by LikeShootingStars** [comment]
Same here: Folder structure and .md files with right names and titles in the files present. What is not present is the actual text.

Here an example running the command as `sudo bash bg2obs.sh -v NIV -acyi`:

<img width="255" alt="Screenshot 2024-01-25 at 21 28 48" src="https://github.com/selfire1/BibleGateway-to-Obsidian/assets/144913586/5f506990-3191-4ecb-a6f2-f5c522cbe293">

At the same time, my terminal gives me following message:

```
internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- clipboard (LoadError)
	from <internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from bg2md.rb:78:in `<main>'
```

This is on a Mac with Sonoma 12.4.1 running.

**Comment by selfire1** [comment]
Were you able to install the `clipboard` gem without problems?

**Comment by LikeShootingStars** [comment]
Thanks so much @selfire1 – That did it for me!
