### ISSUE TITLE
"Syntax Error near unexpected token 'newline' " 

### ISSUE THREAD

**Issue by lukeorafferty** [selfire1/BibleGateway-to-Obsidian#52]
I'm trying to run the script on my Chromebook but am getting the following error:

bg2obs.sh: line 7: syntax error near unexpected token `newline'
bg2obs.sh: line 7: `<!DOCTYPE html>'

Any ideas what I can do to resolve?

**Comment by selfire1** [comment]
Hi @lukeorafferty, I can't reproduce this error. Can you send a screenshot of the error message and which command you used?

**Comment by selfire1** [comment]
stale.

**Comment by selfire1** [comment]
stale
