### ISSUE TITLE
Chinese version

### ISSUE THREAD

**Issue by junwhuan** [selfire1/BibleGateway-to-Obsidian#53]
Hi,

First of all, thank you very much for the tool and the study bible tool. Really appreciated!

I tried to download the Chinese version from biblegateway, but I got error. I'm not ruby coder, so may I know why it happened? 

Thanks,
John
<img width="1100" alt="image" src="https://github.com/selfire1/BibleGateway-to-Obsidian/assets/93282765/8f477870-b10b-44b4-8330-fc2142033b56">

**Comment by selfire1** [comment]
Hi, glad you find this tool helpful!

Were you able to install the `clipboard` gem correctly? (possibly related: #50)

**Comment by junwhuan** [comment]
BTW, the first part
Place both scripts (bg2md.rb and bg2obs.sh) in the same directory, open your terminal application, and navigate to that directory with commands like the following:

I don't see bg2md.rb in your repository. Can you clarify it? Thanks!

**Comment by selfire1** [comment]
You'll need to download `bg2md.rb` from [this separate repository](https://github.com/jgclark/BibleGateway-to-Markdown/tree/7aaa4cdaba5d8ebb2e7e3fa5ace7de96c1534846). Then you can place the ruby script in the same folder as the shell script.

If you use git, you can also [pull the submodules](https://stackoverflow.com/questions/1030169/pull-latest-changes-for-all-git-submodules) and copy the ruby file into the directory.

**Comment by junwhuan** [comment]
Thank you! It's working now.
