### ISSUE TITLE
Download and combined two/multiple languages together

### ISSUE THREAD

**Issue by junwhuan** [selfire1/BibleGateway-to-Obsidian#54]
Hi Thanks for the tool. Is there anyway to have multiple languages combined downloading? For example, in my case, I would like to have two or three different versions bibles together to help me better understand. Would it be possible? Thanks!

**Comment by selfire1** [comment]
Hi! Would it be a solution for you to download a few different versions and simply have them in different folders? That could be accomplished by running the script multiple times with `-v` for version or `-l` for language.

**Comment by selfire1** [comment]
closed since stale
