### ISSUE TITLE
Refer in verse instead of the chapter

### ISSUE THREAD

**Issue by junwhuan** [selfire1/BibleGateway-to-Obsidian#55]
Hi, is there anyway to let the graph view to refer to verse instead of the chapter?
Please see screenshots.
![WX20240210-181339](https://github.com/selfire1/BibleGateway-to-Obsidian/assets/93282765/d4d1cf28-5f4b-4dd2-837c-ca2637fe6a95)

**Comment by selfire1** [comment]
As far as I know this is not possible at the moment. There is a feature request in the Obsidian forum that is related: [Display headings and blocks in graph view - Feature requests](https://forum.obsidian.md/t/display-headings-and-blocks-in-graph-view/6653).
