### ISSUE TITLE
Getting "BibleGateway is empty" error when downloading other versions

### ISSUE THREAD

**Issue by NathanNoye** [selfire1/BibleGateway-to-Obsidian#57]
**Steps that might resolve the issue**
- [x] I have downloaded the `bg2md.rb` file from [jgclark/BibleGateway-to-Markdown](https://github.com/jgclark/BibleGateway-to-Markdown/tree/7aaa4cdaba5d8ebb2e7e3fa5ace7de96c1534846) and placed it in the same folder as the `bg2obs.sh` file.
- [x] I have run `gem install colorize optparse clipboard` (or `sudo gem install colorize optparse clipboard`)

**Describe the bug**
Error: the data returned from BibleGateway is empty, so stopping. Please check your usage, and if still a problem, please raise an issue on GitHub.

I was able to download the CSB but can't download other versions. Not sure if anyone else has run into this but any help is appreciated.

I'm running Ruby v3.0.0

Note - I can confirm that JGClark's script works and is able to fetch from biblegateway.

**Comment by NathanNoye** [comment]
Fixed it - I changed something thinking it would only affect formatting the chapters to put them in order in obsidian so I changed it back.

**Comment by selfire1** [comment]
Glad to hear it ended up working for you!
